Some refactoring of the i3blocks scripts
Trying to clean up my error handling a bit.

diff --git a/dotfiles/common/.local/lib/i3blocks/paout b/dotfiles/common/.local/lib/i3blocks/paout
--- a/dotfiles/common/.local/lib/i3blocks/paout
+++ b/dotfiles/common/.local/lib/i3blocks/paout
@@ -1,9 +1,43 @@
 #!/bin/bash
 
-# Load devices. This script looks for 2 sinks defined in ~/.config/pulse/local_devices:
+# This block allows you to control the volume of 2 named PA sinks (audio
+# outputs): normally your headphones or speakers.
+#
+# This script looks for 2 sinks defined in ~/.config/pulse/local_devices:
 #  * headphones=<device name of your headphones>
 #  * speakers=<device name of your speakers/line out>
 # You can get more info on this by running "pacmd list-sinks".
+
+# log prints a message with an optional priority, which controls the color also
+# printed if a terminal is present. Messages always go to standard error.
+#
+# level is optional, and if not specified defaults to info.
+log() {
+  local message="$1"
+  local level="$2"
+  declare -A colors=(
+    ["error"]="31"   # red
+    ["warning"]="33" # yellow
+    ["ok"]="32"      # green
+    ["info"]="1"     # bold
+    ["reset"]="0"    # here just to note reset code
+  )
+  if [[ -z "${level}" ]] || [[ -z "${colors[$level]}" ]]; then
+    level="info"
+  fi
+  if [[ -t 1 ]]; then
+    echo -e "\e[${colors[$level]}m${message}\e[0m" 1>&2
+  else
+    echo "${message}" 1>&2
+  fi
+}
+
+# log_fatal is a "log MESSAGE error" followed by an "exit 1".
+log_fatal() {
+  local message="$1"
+  log "${message}" error
+  exit 1
+}
 
 declare -A pa_devices
 while read -r line; do
@@ -12,43 +46,32 @@ while read -r line; do
 done < "${HOME}/.config/pulse/local_devices"
 
 if [[ -z "${pa_devices[headphones]}" ]]; then
-  echo "please define your headphones device in ~/.config/pulse/local_devices"
-  exit 127
+  log_fatal "fatal: please define your headphones device in ~/.config/pulse/local_devices"
 fi
 
 if [[ -z "${pa_devices[speakers]}" ]]; then
-  echo "please define your speakers device in ~/.config/pulse/local_devices"
-  exit 127
+  log_fatal "fatal: please define your speakers device in ~/.config/pulse/local_devices"
 fi
 
 # The mixer real-time signal. This will signal to the mixer to immediately
 # update its volume reading upon switching inputs via this block.
 mixer_signal="10"
 
-# exit_if_error exits with error 127, printing the error code given to it to
-# stderr if it is non-zero.
-exit_if_error() {
-  local source="$1"
-  local code="$2"
-  if [[ ${code} != "0" ]]; then
-    echo "${source} exited with error ${code}" >&2
-    exit 127
-  fi
-}
-
 # default_sink gets the default sink name.
 default_sink() {
   local pacmd_out=""
-  pacmd_out=($(pacmd stat | grep 'Default sink name'))
-  exit_if_error "fetching default sink" "$?"
+  if ! pacmd_out=($(pacmd stat | grep 'Default sink name')); then
+    return 1
+  fi
   echo "${pacmd_out[-1]}"
 }
 
 # sink_id gets the sink ID for a specific name.
 sink_id() {
   local name="$1"
-  pactl_out=($(pactl list short sinks | grep "${name}"))
-  exit_if_error "fetching sink ID" "$?"
+  if ! pactl_out=($(pactl list short sinks | grep "${name}")); then
+    return 1
+  fi
   echo "${pactl_out[0]}"
 }
 
@@ -56,8 +79,9 @@ sink_id() {
 # or speakers.
 format() {
   local sink_name=""
-  sink_name="$(default_sink)"
-  exit_if_error "default_sink" "$?"
+  if ! sink_name="$(default_sink)"; then
+    return 1
+  fi
   if [[ "${sink_name}" == "${pa_devices[headphones]}" ]]; then
     echo ""
   else
@@ -71,11 +95,13 @@ move_sink_inputs() {
   local old="$1"
   local new="$2"
   local sink_inputs=""
-  sink_inputs=$(pactl list short sink-inputs | grep -E "^[0-9]{1,}[[:space:]]{1,}${old}" | awk '{print $1}')
-  exit_if_error "fetching sink inputs" "$?"
+  if ! sink_inputs=$(pactl list short sink-inputs | grep -E "^[0-9]{1,}[[:space:]]{1,}${old}" | awk '{print $1}'); then
+    return 1
+  fi
   for input in ${sink_inputs}; do
-    pacmd move-sink-input "${input}" "${new}"
-    exit_if_error "pacmd move-sink-input" "$?"
+    if ! pacmd move-sink-input "${input}" "${new}"; then
+      return 1
+    fi
   done
 }
 
@@ -85,10 +111,12 @@ toggle_default() {
   local current_id=""
   local new=""
   local new_id=""
-  current="$(default_sink)"
-  exit_if_error "finding current input" "$?"
-  current_id="$(sink_id "${current}")"
-  exit_if_error "finding sink ID for current input" "$?"
+  if ! current="$(default_sink)"; then
+    log_fatal "fatal: error locating current input"
+  fi
+  if ! current_id="$(sink_id "${current}")"; then
+    log_fatal "fatal: error locating sink ID for current input"
+  fi
   case "${current}" in
     "${pa_devices[headphones]}")
       new="${pa_devices[speakers]}"
@@ -97,18 +125,18 @@ toggle_default() {
       new="${pa_devices[headphones]}"
       ;;
     *)
-      echo "could not determine input type for default input: ${current}" >&2
-      exit 127
+      log_fatal "fatal: could not determine input type for default input: ${current}"
       ;;
   esac
-  new_id="$(sink_id "${new}")"
-  exit_if_error "finding sink ID for new input" "$?"
-
-  pactl set-default-sink "${new}"
-  exit_if_error "pactl set-default-sink" "$?"
-
-  move_sink_inputs "${current_id}" "${new_id}"
-  exit_if_error "moving sink inputs to new output" "$?"
+  if ! new_id="$(sink_id "${new}")"; then
+    log_fatal "fatal: error finding sink ID for new input"
+  fi
+  if ! pactl set-default-sink "${new}"; then
+    log_fatal "fatal: error running pactl set-default-sink"
+  fi
+  if ! move_sink_inputs "${current_id}" "${new_id}"; then
+    log_fatal "fatal: error moving sink inputs to new output"
+  fi
 
   # Update the mixer's volume.
   kill -s "RTMIN+${mixer_signal}" "$(pidof i3blocks)"
@@ -120,4 +148,6 @@ case $BLOCK_BUTTON in
   3) toggle_default ;;  # right click, toggle default
 esac
 
-format
+if ! format; then
+  log_fatal "fatal: error rendering block"
+fi
diff --git a/dotfiles/common/.local/lib/i3blocks/pasource b/dotfiles/common/.local/lib/i3blocks/pasource
--- a/dotfiles/common/.local/lib/i3blocks/pasource
+++ b/dotfiles/common/.local/lib/i3blocks/pasource
@@ -1,9 +1,43 @@
 #!/bin/bash
 
-# Load devices. This script looks for 2 sinks defined in ~/.config/pulse/local_devices:
+# This block allows you to control the volume of 2 named PA sinks (audio
+# outputs): normally your headphones or speakers.
+#
+# This script looks for 2 sinks defined in ~/.config/pulse/local_devices:
 #  * headset=<device name of your headset>
 #  * camera=<device name of your camera mic, or onboard mic for laptops>
 # You can get more info on this by running "pacmd list-sources".
+
+# log prints a message with an optional priority, which controls the color also
+# printed if a terminal is present. Messages always go to standard error.
+#
+# level is optional, and if not specified defaults to info.
+log() {
+  local message="$1"
+  local level="$2"
+  declare -A colors=(
+    ["error"]="31"   # red
+    ["warning"]="33" # yellow
+    ["ok"]="32"      # green
+    ["info"]="1"     # bold
+    ["reset"]="0"    # here just to note reset code
+  )
+  if [[ -z "${level}" ]] || [[ -z "${colors[$level]}" ]]; then
+    level="info"
+  fi
+  if [[ -t 1 ]]; then
+    echo -e "\e[${colors[$level]}m${message}\e[0m" 1>&2
+  else
+    echo "${message}" 1>&2
+  fi
+}
+
+# log_fatal is a "log MESSAGE error" followed by an "exit 1".
+log_fatal() {
+  local message="$1"
+  log "${message}" error
+  exit 1
+}
 
 declare -A pa_devices
 while read -r line; do
@@ -12,43 +46,32 @@ while read -r line; do
 done < "${HOME}/.config/pulse/local_devices"
 
 if [[ -z "${pa_devices[headset]}" ]]; then
-  echo "please define your headset device in ~/.config/pulse/local_devices"
-  exit 127
+  log_fatal "fatal: please define your headset device in ~/.config/pulse/local_devices"
 fi
 
 if [[ -z "${pa_devices[camera]}" ]]; then
-  echo "please define your camera device in ~/.config/pulse/local_devices"
-  exit 127
+  log_fatal "fatal: please define your camera device in ~/.config/pulse/local_devices"
 fi
 
 # The mixer real-time signal. This will signal to the mixer to immediately
 # update its volume reading upon switching inputs via this block.
 mixer_signal="11"
 
-# exit_if_error exits with error 127, outputing the error code given to it to
-# stderr if it is non-zero.
-exit_if_error() {
-  local source="$1"
-  local code="$2"
-  if [[ ${code} != "0" ]]; then
-    echo "${source} exited with error ${code}" >&2
-    exit 127
-  fi
-}
-
 # default_source gets the default source name.
 default_source() {
   local pacmd_out=""
-  pacmd_out=($(pacmd stat | grep 'Default source name'))
-  exit_if_error "fetching default source" "$?"
+  if ! pacmd_out=($(pacmd stat | grep 'Default source name')); then
+    return 1
+  fi
   echo "${pacmd_out[-1]}"
 }
 
 # source_id gets the source ID for a specific name.
 source_id() {
   local name="$1"
-  pactl_out=($(pactl list short sources | grep "${name}"))
-  exit_if_error "fetching source ID" "$?"
+  if ! pactl_out=($(pactl list short sources | grep "${name}")); then
+    return 1
+  fi
   echo "${pactl_out[0]}"
 }
 
@@ -56,8 +79,9 @@ source_id() {
 # camera.
 format() {
   local source_name=""
-  source_name="$(default_source)"
-  exit_if_error "default_source" "$?"
+  if ! source_name="$(default_source)"; then
+    return 1
+  fi
   if [[ "${source_name}" == "${pa_devices[headset]}" ]]; then
     echo ""
   else
@@ -71,11 +95,13 @@ move_source_outputs() {
   local old="$1"
   local new="$2"
   local source_outputs=""
-  source_outputs=$(pactl list short source-outputs | grep -E "^[0-9]{1,}[[:space:]]{1,}${old}" | awk '{print $1}')
-  exit_if_error "fetching source outputs" "$?"
+  if ! source_outputs=$(pactl list short source-outputs | grep -E "^[0-9]{1,}[[:space:]]{1,}${old}" | awk '{print $1}'); then
+    return 1
+  fi
   for input in ${source_outputs}; do
-    pacmd move-source-output "${input}" "${new}"
-    exit_if_error "pacmd move-source-output" "$?"
+    if ! pacmd move-source-output "${input}" "${new}"; then
+      return 1
+    fi
   done
 }
 
@@ -85,10 +111,12 @@ toggle_default() {
   local current_id=""
   local new=""
   local new_id=""
-  current="$(default_source)"
-  exit_if_error "finding current source" "$?"
-  current_id="$(source_id "${current}")"
-  exit_if_error "finding source ID for current input" "$?"
+  if ! current="$(default_source)"; then
+    log_fatal "fatal: error finding current source"
+  fi
+  if ! current_id="$(source_id "${current}")"; then
+    log_fatal "fatal: error finding source ID for current input"
+  fi
   case "${current}" in
     "${pa_devices[headset]}")
       new="${pa_devices[camera]}"
@@ -97,18 +125,18 @@ toggle_default() {
       new="${pa_devices[headset]}"
       ;;
     *)
-      echo "could not determine source type for default source: ${current}" >&2
-      exit 127
+      log_fatal "fatal: could not determine source type for default source: ${current}"
       ;;
   esac
-  new_id="$(source_id "${new}")"
-  exit_if_error "finding ID for new source" "$?"
-
-  pactl set-default-source "${new}"
-  exit_if_error "pactl set-default-source" "$?"
-
-  move_source_outputs "${current_id}" "${new_id}"
-  exit_if_error "moving source outputs to new source" "$?"
+  if ! new_id="$(source_id "${new}")"; then
+    log_fatal "fatal: error finding ID for new source" "$?"
+  fi
+  if ! pactl set-default-source "${new}"; then
+    log_fatal "fatal: error running pactl set-default-source"
+  fi
+  if ! move_source_outputs "${current_id}" "${new_id}"; then
+    log_fatal "fatal: error moving source outputs to new source"
+  fi
 
   # Update the mixer's volume.
   kill -s "RTMIN+${mixer_signal}" "$(pidof i3blocks)"
@@ -120,4 +148,6 @@ case $BLOCK_BUTTON in
   3) toggle_default ;;  # right click, toggle default
 esac
 
-format
+if ! format; then
+  log_fatal "fatal: error rendering block"
+fi
diff --git a/dotfiles/common/.local/lib/i3blocks/restic b/dotfiles/common/.local/lib/i3blocks/restic
--- a/dotfiles/common/.local/lib/i3blocks/restic
+++ b/dotfiles/common/.local/lib/i3blocks/restic
@@ -3,15 +3,35 @@
 # The time to warn when there hasn't been a backup in a while, in seconds.
 warn_no_backup="86400"
 
-# exit_if_error exits with error 127, printing the error code given to it to
-# stderr if it is non-zero.
-exit_if_error() {
-  local source="$1"
-  local code="$2"
-  if [[ ${code} != "0" ]]; then
-    echo "${source} exited with error ${code}" >&2
-    exit 127
+# log prints a message with an optional priority, which controls the color also
+# printed if a terminal is present. Messages always go to standard error.
+#
+# level is optional, and if not specified defaults to info.
+log() {
+  local message="$1"
+  local level="$2"
+  declare -A colors=(
+    ["error"]="31"   # red
+    ["warning"]="33" # yellow
+    ["ok"]="32"      # green
+    ["info"]="1"     # bold
+    ["reset"]="0"    # here just to note reset code
+  )
+  if [[ -z "${level}" ]] || [[ -z "${colors[$level]}" ]]; then
+    level="info"
   fi
+  if [[ -t 1 ]]; then
+    echo -e "\e[${colors[$level]}m${message}\e[0m" 1>&2
+  else
+    echo "${message}" 1>&2
+  fi
+}
+
+# log_fatal is a "log MESSAGE error" followed by an "exit 1".
+log_fatal() {
+  local message="$1"
+  log "${message}" error
+  exit 1
 }
 
 # load_status returns the LoadState of the restic unit. This is to make sure
@@ -19,8 +39,9 @@ exit_if_error() {
 # even if the unit does not exist.
 load_status() {
   local systemctl_out=""
-  systemctl_out=$(systemctl --user --property=LoadState show restic.service)
-  exit_if_error "systemctl" "$?"
+  if ! systemctl_out="$(systemctl --user --property=LoadState show restic.service)"; then 
+    return 1
+  fi
   IFS="=" read -r -a load_status <<< "${systemctl_out}"
   echo "${load_status[1]}"
 }
@@ -29,15 +50,17 @@ load_status() {
 restic_status() {
   # chain in load_status, just in case the unit has not been found.
   local load_status_out=""
-  load_status_out="$(load_status)"
-  exit_if_error "checking load status" "$?"
+  if ! load_status_out="$(load_status)"; then
+    return 1
+  fi
   if [[ "${load_status_out}" == "not-found" ]]; then
     echo "${load_status_out}"
     return
   fi
   local systemctl_out=""
-  systemctl_out=$(systemctl --user --property=ActiveState show restic.service)
-  exit_if_error "systemctl" "$?"
+  if ! systemctl_out="$(systemctl --user --property=ActiveState show restic.service)"; then
+    return 1
+  fi
   IFS="=" read -r -a active_state <<< "${systemctl_out}"
   echo "${active_state[1]}"
 }
@@ -46,8 +69,9 @@ restic_status() {
 # of the time of day.
 format_hourglass() {
   local mod=""
-  mod=$(( $(date +%s) % 3 ))
-  exit_if_error "fetching system date" "$?"
+  if ! mod=$(( $(date +%s) % 3 )); then
+    return 1
+  fi
   case "${mod}" in
     "0")
       echo ""
@@ -71,17 +95,20 @@ format_check_ok() {
   local systemctl_out=""
   local exit_timestamp_unix=""
   local current_timestamp_unix=""
-  systemctl_out=$(systemctl --user --property=ExecMainExitTimestamp show restic.service)
-  exit_if_error "systemctl" "$?"
+  if ! systemctl_out="$(systemctl --user --property=ExecMainExitTimestamp show restic.service)"; then
+    return 1
+  fi
   IFS="=" read -r -a exit_timestamp <<< "${systemctl_out}"
   if [[ -z "${exit_timestamp[1]}" ]]; then
     exit_timestamp_unix="0"
   else
-    exit_timestamp_unix="$(date +%s --date="${exit_timestamp[1]}")"
+    if ! exit_timestamp_unix="$(date +%s --date="${exit_timestamp[1]}")"; then
+      return 1
+    fi
   fi
-  exit_if_error "converting datestamp to unix time" "$?"
-  current_timestamp_unix="$(date +%s)"
-  exit_if_error "getting current UNIX time" "$?"
+  if ! current_timestamp_unix="$(date +%s)"; then
+    return 1
+  fi
   if (( current_timestamp_unix - warn_no_backup > exit_timestamp_unix )); then
     echo -e "\n\n#ffa500"
   else
@@ -98,13 +125,15 @@ format_check_ok() {
 format() {
   local out=""
   local status=""
-  status="$(restic_status)"
-  exit_if_error "restic_status" "$?"
+  if ! status="$(restic_status)"; then
+    return 1
+  fi
   case "${status}" in
     "active")
       # Backup job is running, but we want to display a fancy animated icon.
-      out="$(format_hourglass)"
-      exit_if_error "fetching in-progress animation" "$?"
+      if ! out="$(format_hourglass)"; then
+        return 1
+      fi
       echo "${out}"
       ;;
     "failed")
@@ -113,8 +142,9 @@ format() {
       ;;
     "inactive")
       # Just check to see if the job has run recently
-      out="$(format_check_ok)"
-      exit_if_error "checking for OK status" "$?"
+      if ! out="$(format_check_ok)"; then
+        return 1
+      fi
       echo "${out}"
       ;;
     *)
@@ -128,12 +158,17 @@ case $BLOCK_BUTTON in
     i3-msg 'exec --no-startup-id i3-sensible-terminal --title "Restic Status" -e "systemctl --user status restic.service"' >/dev/null
     ;;
   "3")
-    status="$(restic_status)"
-    exit_if_error "restic_status" "$?"
+    if ! status="$(restic_status)"; then
+      log_fatal "fatal: error checking restic status"
+    fi
     if [[ "${status}" != "active" ]]; then
-      systemctl --user start restic.service
+      if ! systemctl --user start restic.service; then
+        log_fatal "fatal: error starting restic.service user service to run backup"
+      fi
     fi
     ;;
 esac
 
-format
+if ! format; then
+  log_fatal "fatal: error rendering block"
+fi
